openapi: 3.0.3
info:
  title: 'Hospital Management System API Docs'
  description: 'Hospital Management System API Docs'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/login-user:
    post:
      summary: ''
      operationId: postApiLoginUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/patients:
    post:
      summary: 'PATIENTS :: List'
      operationId: pATIENTSList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/patients/add:
    post:
      summary: 'PATIENTS :: Store'
      operationId: pATIENTSStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier_number:
                  type: string
                  description: "'user_id' => 'nullable|string|max:255|unique:people',\n'person_type_id' => 'required|integer|exists:person_types,id',\n'city_id' => 'required|integer|exists:cities,id',."
                  example: facilis
                blood_group:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: szynwkxeobxdmnknlln
                email:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mathilde.fay@example.net
                city_id:
                  type: integer
                  description: ''
                  example: 20
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: znuatdyopzucwm
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: lmpsle
                date_of_birth:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-06-27T17:48:24'
                gender:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: cqd
                phones:
                  type: string
                  description: "'phone' => 'nullable|string|max:20|unique:phones,phone_number',. Must not be greater than 20 characters."
                  example: kgkjb
              required:
                - city_id
                - first_name
                - last_name
      security: []
  /api/patients/show:
    post:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/patients/bulk-upload-patients:
    post:
      summary: ''
      operationId: postApiPatientsBulkUploadPatients
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/patients/update:
    post:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier_number:
                  type: string
                  description: ''
                  example: ipsa
                blood_group:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ev
                city_id:
                  type: integer
                  description: ''
                  example: 2
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: gybqjndoizeeytrkrhvov
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: gzqiaczmdncepqrfxumo
                date_of_birth:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-06-27T17:48:24'
                gender:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: qozkxresh
                phones:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: shpeqcaazi
              required:
                - city_id
                - first_name
                - last_name
      security: []
  /api/patients/delete:
    post:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: string
                  description: ''
                  example: maiores
              required:
                - patient_id
      security: []
  /api/patient-visits:
    post:
      summary: 'PATIENT VISITS :: List'
      operationId: pATIENTVISITSList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/patient-visits/add:
    post:
      summary: 'PATIENT VISITS :: Store'
      operationId: pATIENTVISITSStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/patient-visits/show:
    post:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/logout-user:
    post:
      summary: ''
      operationId: postApiLogoutUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/cities:
    post:
      summary: 'CITIES :: List'
      operationId: cITIESList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/departments:
    post:
      summary: 'DEPARTMENTS :: List'
      operationId: dEPARTMENTSList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultation:
    post:
      summary: ''
      operationId: postApiConsultation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultation/add:
    post:
      summary: 'CONSULTATION :: Store'
      operationId: cONSULTATIONStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultation/show:
    post:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultation/update:
    post:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                current_medications:
                  type: string
                  description: "'patient_visit_id' => 'required|exists:patient_visits,id',."
                  example: dolores
                height_cm:
                  type: number
                  description: ''
                  example: 6798677.0
                weight_kg:
                  type: number
                  description: ''
                  example: 20304971.619
                allergies:
                  type: string
                  description: ''
                  example: nostrum
                reason_for_visit:
                  type: string
                  description: ''
                  example: voluptatem
                blood_pressure:
                  type: string
                  description: ''
                  example: mollitia
                heart_rate:
                  type: number
                  description: ''
                  example: 90.3039
                temperature:
                  type: number
                  description: ''
                  example: 5590.0
                respiratory_rate:
                  type: number
                  description: ''
                  example: 45.01
                oxygen_saturation:
                  type: number
                  description: ''
                  example: 578.0
                past_medical_history:
                  type: string
                  description: ''
                  example: odit
                family_medical_history:
                  type: string
                  description: ''
                  example: laborum
                immunization_history:
                  type: string
                  description: ''
                  example: ratione
                doctors_notes:
                  type: string
                  description: ''
                  example: odit
                diagnosis_ids:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
                custom_diagnosis:
                  type: string
                  description: ''
                  example: vel
                next_appointment:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-06-27T17:48:24'
      security: []
  /api/consultation/get-consultation-data:
    post:
      summary: 'CONSULTATION :: Get consultation data.'
      operationId: cONSULTATIONGetConsultationData
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultation/create-or-retrieve:
    post:
      summary: 'CONSULTATION :: Create a new consultation or return the existing consultation.'
      operationId: cONSULTATIONCreateANewConsultationOrReturnTheExistingConsultation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_visit_id:
                  type: string
                  description: ''
                  example: assumenda
              required:
                - patient_visit_id
      security: []
  '/api/consultation/patient-details/{patient_visit_id}':
    get:
      summary: 'CONSULTATION :: Get Patient Details By Patient Visit Id'
      operationId: cONSULTATIONGetPatientDetailsByPatientVisitId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: patient_visit_id
        description: 'The ID of the patient visit.'
        example: earum
        required: true
        schema:
          type: string
  /api/diagnosis/diagnosis-codes:
    post:
      summary: 'DIAGNOSIS CODES :: List'
      operationId: dIAGNOSISCODESList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/diagnosis/save-diagnosis:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/investigations:
    get:
      summary: 'INVESTIGATIONS :: List'
      operationId: iNVESTIGATIONSList
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/patient-investigations/patient-investigations/{consultation_id}/investigations':
    post:
      summary: 'PATIENT INVESTIGATIONS :: Store'
      operationId: pATIENTINVESTIGATIONSStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                investigation_ids:
                  type: array
                  description: ''
                  example: null
                  items:
                    type: string
      security: []
    parameters:
      -
        in: path
        name: consultation_id
        description: 'The ID of the consultation.'
        example: quod
        required: true
        schema:
          type: string
  '/api/patient-investigations/patient-investigations/{consultation_id}/investigations/{investigation_id}':
    put:
      summary: 'PATIENT INVESTIGATIONS :: Update'
      operationId: pATIENTINVESTIGATIONSUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: ''
                  example: non
                results:
                  type: string
                  description: ''
                  example: a
              required:
                - status
      security: []
    parameters:
      -
        in: path
        name: consultation_id
        description: 'The ID of the consultation.'
        example: magni
        required: true
        schema:
          type: string
      -
        in: path
        name: investigation_id
        description: 'The ID of the investigation.'
        example: enim
        required: true
        schema:
          type: string
  '/api/people/people/{person_id}/phones':
    post:
      summary: 'PHONES :: Store'
      operationId: pHONESStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: 'y'
              required:
                - phone_number
      security: []
    parameters:
      -
        in: path
        name: person_id
        description: 'The ID of the person.'
        example: facilis
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
